databases:
  - name: mongodb
    ipAllowList: []
services:
  - type: pserv
    name: mongodb
    plan: free
    env: docker
    autoDeploy: true
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: MONGODB_URL
    buildCommand: "npm run build"
    startCommand: "npm start"